databases:
  - name: color-tips_DB
    databaseName: color-tips_DB
    user: color-tips
    region: singapore

services:
  - type: web
    name: color-tips
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: color-tips_DB
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false

