databases:
  - name: colortips_db
    databaseName: colortips_db
    user: ryosuke
    region: singapore

services:
  - type: web
    name: colortips
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: colortips_db
          property: connectionString
      - key: RAILS_MASTER_KEY'
        sync: false

