databases:
  - name: colortips_db
    databaseName: colortips_db
    user: ryosuke
    region: singapore

services:
  - type: web
    name: colortips_db
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: <%= ENV['DATABASE_URL'] %>
        fromDatabase:
          name: colortips_db
          property: connectionString
      - key: <%= ENV['RAILS_MASTER_KEY'] %>
        sync: false

